DM-40046: Fix unresolved merge conflict with gen3.sqlite3
lsst/ap_verify_ci_hits2015 pull request #47
Opened 2023-07-20 20:51 UTC by erinleighh

2023-07-20 21:33 UTC, kfindeisen requested changes
I'm assuming that `ap_verify` runs with this version of the registry, but I'd feel better if the `export.yaml` were re-synced so we could see what's inside.

2023-07-20 21:33 UTC, kfindeisen commented on preloaded/gen3.sqlite3
Did you run `make_preloaded_export.py` after updating the registry? I'm expecting that, like on #45, the only changes would be the dataset IDs (which apparently don't interfere with import), but it's a good sanity check that the registry contains what we think it does.

2023-07-20 21:47 UTC, erinleighh commented on preloaded/gen3.sqlite3
Yes, I ran `make_preloaded_export.py` after updating, which didn't have any issues. I'll re-sync the `export.yaml`.

2023-07-21 17:39 UTC, kfindeisen commented on preloaded/gen3.sqlite3
From Slack discussion, it turns out that the registry really is identical down to the dataset IDs, so there's nothing to push.

2023-07-21 17:39 UTC, kfindeisen approved these changes

2023-07-21 18:22 UTC, merged