DM-44592: Remove ApTemplate from ap_pipe/ap_verify and docs
lsst/ap_verify_ci_hits2015 pull request #59
Opened 2024-09-12 16:20 UTC by leeskelvin

{Summary of changes. Prefix PR title with JIRA issue.}

****

- [x] Did you run `ap_verify.py` on this dataset?
- [x] If you made changes to `scripts/`, should those changes be propagated to [ap_verify_dataset_template](https://github.com/lsst-dm/ap_verify_dataset_template/), or are they specific to this data set?
- [x] Are the Sphinx documentation and readme up-to-date?

2024-09-14 00:46 UTC, isullivan requested changes
Two of the calibs scripts should probably not be removed on this ticket.

2024-09-14 00:46 UTC, isullivan commented on scripts/generate_calibs_gen3.sh
I don't think we should remove the calibs scripts on this ticket.

2024-09-14 00:46 UTC, isullivan commented on scripts/generate_calibs_gen3_science.sh
I don't think you should remove this file on this ticket.

2024-09-16 12:41 UTC, leeskelvin commented
These files restored:
* `scripts/generate_calibs_gen3.sh`
* `scripts/generate_calibs_gen3_science.sh`

2024-09-16 12:43 UTC, merged